name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm run lint
  test:
    needs: build-lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - uses: OctopusDeploy/install-octopus-cli-action@v1
      - run: npm test